name = str(input('Digite seu nome completo: ')).strip()
print('\nAnalisando seu nome {}...\n'.format(name))
print('Seu nome em maiúsculas: {}'.format(name.upper()))
print('Seu nome em minúsculas: {}'.format(name.lower()))
print('Seu nome tem ao todo {} letras'.format(len(name) - name.count(' ')))
print('Seu primeiro nome tem: {} letras\n'.format(name.find(' ')))