text = str(input('Digite uma frase: ')).strip()
print('\nFrase: {}....\n'.format(text))
print('A letra A aparece {} vezes na frase.\n'.format(text.lower().count('a')))
print('Primeira letra A aparece na posição {}.\n'.format(text.lower().find('a') + 1))
print('Última letra A aparece na posição {}.\n'.format(text.lower().rfind('a') + 1))