name = str(input('Digite seu nome completo: ')).strip()
print('\nAnálisando o nome {}...\n'.format(name))
n = name.split()
print('Primeiro nome: {}'.format(n[0]))
print('Último nome: {}\n'.format(n[len(n) - 1]))